### ISSUE TITLE
GetComponentAttribute 사용 시의 버그

### ISSUE THREAD

**Issue by BeautyfullCastle** [jinnin0105/UnityComponentAutoInjector#5]
GetComponent를 사용할 시 찾을 수 없는 타입을 써도 Failed가 뜨지 않습니다.

**Comment by jinnin0105** [comment]
유니티 기본내장 되어있는 GetComponent(Type type) 타입이 있는 null 을 반환하여 생기는 문제.
ToString 으로 변환 후 체크로 해결.
